services:
  mongodb_container:
      image: mongo:latest
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: bradySDC
      ports:
        - 27017:27017
      volumes:
        - mongodb:/data/db
  postgresContainer:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: bradySDC
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 3000:3000

volumes:
  postgres:
    driver: local
  mongodb:
    driver: local