services:
  mongodb_container:
      image: mongo:latest
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGOUSR}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGOPASS}
      ports:
        - ${MONGOPORT}:${MONGOPORT}
      volumes:
        - mongodb:/data/db
  postgres_container:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRESPASS}
    ports:
      -  ${POSTGRESPORT}:${POSTGRESPORT}
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 3000:3000

volumes:
  postgres:
    driver: local
  mongodb:
    driver: local