services:
  postgres_container:
    image: postgres:latest
    container_name: ${PG_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USR}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      -  ${PG_PORT}:${PG_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data

  redis_container:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME}
    restart: always
    ports:
      -  ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/var/lib/redis/data


  backend:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 3000:3000

volumes:
  postgres:
    driver: local
  redis:
    driver: local